### ISSUE TITLE
Export-Funktion: Sprache im Core nicht mehr enthalten.

### ISSUE THREAD

**Issue by thorol** [tbaddade/redaxo_wildcard#74]
Der Export wirft einen Fehler, wenn in der Datenbank-Tabelle noch Einträge mit einer Sprache vohanden sind, die der Core nicht mehr kennt. Dies sollte abgefangen werden.

**Error:** Call to a member function getCode() on null
**File:** redaxo/src/addons/sprog/pages/artefact.export.php
**Line:** 41

<details>
<summary>Stacktrace</summary>

| Function                                     | File                                     | Line     |
| -------------------------------------------- | ---------------------------------------- | -------- |
| include                                      | redaxo/src/core/lib/packages/package.php | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php    | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php       | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php    | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php    | 432      |
| rex_be_controller::includeCurrentPageSubPath | redaxo/src/addons/sprog/pages/index.php  | 17       |
| include                                      | redaxo/src/core/lib/packages/package.php | 280      |
| rex_package->includeFile                     | redaxo/src/core/lib/be/controller.php    | 482      |
| rex_be_controller::{closure}                 | redaxo/src/core/lib/util/timer.php       | 57       |
| rex_timer::measure                           | redaxo/src/core/lib/be/controller.php    | 483      |
| rex_be_controller::includePath               | redaxo/src/core/lib/be/controller.php    | 415      |
| rex_be_controller::includeCurrentPage        | redaxo/src/core/backend.php              | 233      |
| require                                      | redaxo/src/core/boot.php                 | 141      |
| require                                      | redaxo/index.php                         | 9        |

</details>
<details>
<summary>System report (REDAXO 5.12.1, PHP 7.4.24, MariaDB 10.6.4)</summary>

| REDAXO        |            |
| ------------: | :--------- |
|       Version | 5.12.1     |

| PHP           |                                |
| ------------: | :----------------------------- |
|       Version | 7.4.24                         |
|       OPcache | no                             |
|        Xdebug | no                             |
|       Warning | Das Setup wird unverschlüsselt durchgeführt. Frontend und Backend sollten grundsätzlich durch HTTPS verschlüsselt aufgerufen werden, um die Privatsphäre zu schützen und den Datenschutz zu gewährleisten. |

| Database      |                |
| ------------: | :------------- |
|       Version | MariaDB 10.6.4 |
| Character set | utf8           |

| Server        |                |
| ------------: | :------------- |
|            OS | Linux          |
|          SAPI | apache2handler |
|     Webserver | Apache/2.4.48  |

| Request       |                     |
| ------------: | :------------------ |
|       Browser | Chrome/94.0.4606.81 |
|      Protocol | HTTP/1.1            |
|         HTTPS | no                  |

| Packages                  |             |
| ------------------------: | :---------- |
|                    backup | 2.7.1       |
|      be_arttec_customizer | 0.0.7       |
|                  be_style | 2.12.1      |
|           be_style/redaxo | 2.12.1      |
|                   bloecks | 3.1.0       |
|          bloecks/cutncopy | 3.1.0       |
|         bloecks/dragndrop | 3.1.0       |
|            bloecks/status | 3.1.0       |
|                   cronjob | 2.8.0       |
|                 developer | 3.9.0       |
|                focuspoint | 3.0.2       |
|                   install | 2.9.1       |
|                  markitup | 3.6.1       |
|                    mblock | 3.2.0       |
|             media_manager | 2.11.1      |
| media_manager_autorewrite | 2.0.1       |
|        media_manager_plus | 2.1.2       |
|                 mediapool | 2.10.1      |
|                  metainfo | 2.8.1       |
|                     mform | 6.0.13      |
|                mform/docs | 1.1         |
|                 phpmailer | 2.10.2      |
|                   project | dev         |
|                 redactor2 | 4.1.0       |
|                 search_it | 6.7.3       |
|   search_it/documentation | 6.7.3       |
|                     sprog | 1.3.0-beta1 |
|                 structure | 2.12.1      |
|         structure/content | 2.12.0      |
|                     users | 2.8.0       |
|                   ydeploy | 1.0.0       |
|                     yform | 3.4.2       |
|               yform/email | 3.4.2       |
|             yform/manager | 3.4.2       |
|     yform_spam_protection | 1.1.0       |
|                  yrewrite | 2.7         |
|  yrewrite_domain_settings | 2.0.2       |

</details>

**Comment by thorol** [comment]
@tbaddade Ja, klappt jetzt, prima danke. In der ersten Spalte wird die "fehlende" ID gezeigt:
![image](https://user-images.githubusercontent.com/25980352/139481627-0e5ea7bf-958c-4905-9137-f762c6106d15.png)

**Comment by tbaddade** [comment]
Danke dein Test … so soll es aussehen.
